### ISSUE TITLE
Auto reattach?

### ISSUE THREAD

**Issue by ofek-a** [bdspen/nodemon_vscode#1]
Is there a way to automatically reattach debugger? Would be even better if this could be toggled on/off easily.

**Comment by bdspen** [comment]
That would certainly make things easier.  I will look into it!

**Comment by weinand** [comment]
Please see these small improvements in the upcoming VS Code 1.14: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#simplified-setup-for-restart-debug-session

See section 'Simplified setup for "Restart debug session"'

**Comment by ofek-a** [comment]
Oh great, so reattaching works just fine in 1.13 as well using `"restart": true`. Thanks for pointing it out :+1: 

Apparently I glossed over that entire section in the README :man_facepalming:

**Comment by weinand** [comment]
The improvement in 1.14 is only that users don't have to deal with ports (and port differences in face of node v8.0 deprecation of "legacy" protocol and ports).
